fabric01:
 hosts:
    apic1:
      apic_host: 172.31.30.2
      apic_username: admin
      apic_password: Day2OPS! 
 vars:
    apic_use_proxy: no
    apic_validate_certs: no
    aci_topology:
      tenant:
      - name: SecureDC
        description: SecureDC tenant provisioned by Galaxy
        app:
        - name: Developement
          epg:
          - name: Web
            bd: Common
            contract:
            - name: internet
              type: consumer
            - name: web_app
              type: consumer
          - name: App
            bd: Common
            contract:
            - name: web_app
              type: provider
          - name: Patch
            bd: Patch
          - name: Repo
            bd: Server_Inside
        bd:
        - name: Common
          subnet:
          - name: 172.16.11.1
            mask: 24
            scope: public
          vrf: SecureDC
        - name: Patch
          subnet:
          - name: 172.16.21.1
            mask: 24
            scope: public
          vrf: SecureDC
        - name: Server_Inside
          vrf: SecureDC
          arp_flooding: yes
        vrf:
        - name: SecureDC
        contract:
        - name: Domain
          scope: tenant
          subject:
          - name: Domain
            filter: FilterDomain       
          - name: RDP
            filter: RDP 
        - name: RDP
          scope: tenant
          subject:
          - name: RDP
            filter: FilterRDP
